[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_remappings = false

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@axelar-network/axelar-gmp-sdk-solidity/contracts/=lib/axelar-gmp-sdk-solidity/contracts/",
]

optimizer = true
optimizer_runs = 1000000
names = true
sizes = true
via_ir = true
ffi = true
ast = true
build_info = true
evm_version = "london"
extra_output_files = ["abi"]
fs_permissions = [{ access = "read", path = "./out" }]

[rpc_endpoints]
dmd_mainnet = "https://rpc.bit.diamonds"
avalanche_fuji = "https://api.avax-test.network/ext/bc/C/rpc"

[etherscan]
dmd_mainnet = { key = "123", url = "https://explorer.bit.diamonds/api" }
